# Site wide configuration
#locale: en_US
#logo: # filename of a logo image that has been placed into your images directory

title: celligrate
author: Yun (Renee) Zhang
email: zhangy@jcvi.org
description: > # this means to ignore newlines until "show_excerpts:"
  An essential software suite for *downstream* cell type characterization and integration from single cell RNA-sequencing experiments
show_excerpts: true # set to true to show excerpts on the homepage
logo: /assets/jcvi.png

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: JCVenterInst
    github:  yunzhang813
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: J. Craig Venter Institute
    #   instance: https://www.jcvi.org/
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - motivation.md
 - FRmatch-vignette.html
 - about.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jemoji
